#!/usr/bin/env node

/*
 * Copyright 2010-2019 Gildas Lormeau
 * contact : gildas.lormeau <at> gmail.com
 *
 * This file is part of SingleFile.
 *
 *   The code in this file is free software: you can redistribute it and/or
 *   modify it under the terms of the GNU Affero General Public License
 *   (GNU AGPL) as published by the Free Software Foundation, either version 3
 *   of the License, or (at your option) any later version.
 *
 *   The code in this file is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 *   General Public License for more details.
 *
 *   As additional permission under GNU AGPL version 3 section 7, you may
 *   distribute UNMODIFIED VERSIONS OF THIS file without the copy of the GNU
 *   AGPL normally required by section 4, provided you include this license
 *   notice and a URL through which recipients can access the Corresponding
 *   Source.
 */

/* global require */

const config = {
	"backEnd": "puppeteer",
	"browserHeadless": true,
	"browserExecutable-path": "",
	"browserWidth": 1280,
	"browserHeight": 720,
	"browserLoadMaxTime": 60000,
	"browserWaitUntil": "networkidle0",
	"browserDebug": false,
	"browserExtensions": [],
	"compressCSS": true,
	"compressHTML": true,
	"filenameTemplate": "",
	"groupDuplicateImages": true,
	"loadDeferredImages": true,
	"loadDeferredImagesMaxIdleTime": 1500,
	"maxResourceSizeEnabled": false,
	"maxResourceSize": 10,
	"removeHiddenElements": true,
	"removeUnusedStyles": true,
	"removeUnusedFonts": true,
	"removeFrames": false,
	"removeImports": true,
	"removeScripts": true,
	"removeAudioSrc": true,
	"removeVideoSrc": true,
	"removeAlternativeFonts": true,
	"removeAlternativeMedias": true,
	"removeAlternativeImages": true,
	"saveRawPage": false,
	"webDriverExecutablePath": ""
};

require("./back-ends/puppeteer.js").getPageData(config).then(pageData => {	


});